clocksource: scx200_hrt: Fix the build
This commit:

  1e49d030dc7c: clocksource: scx200_hrt: Convert scx200 to use clocksource_register_hz

Breaks the build on x86-32:

  drivers/clocksource/scx200_hrt.c: In function ‘init_hrt_clocksource’:
  drivers/clocksource/scx200_hrt.c:95:0: error: unterminated argument list invoking macro "pr_info"
  drivers/clocksource/scx200_hrt.c:84:2: error: ‘pr_info’ undeclared (first use in this function)

It could not possibly have been build tested, because it had this mismerge:

	pr_info("enabling scx200 high-res timer (%s MHz +%d ppm)\n",
	printk(KERN_INFO "enabling scx200 high-res timer (%s MHz +%d ppm)\n",
		mhz27 ? "27":"1", ppm);

Cc: Jim Cromie <jim.cromie@gmail.com>
Cc: John Stultz <john.stultz@linaro.org>
Link: http://lkml.kernel.org/n/tip-jceb26fns5w7tv8edlivhxpa@git.kernel.org
Signed-off-by: Ingo Molnar <mingo@elte.hu>