Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit fd03808aa7b6c8da71f46b5319937bfe22b8dee1, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer