Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 01e504a2e4fa548b446328e3b722e7e08bce9308.

Commit 01e504a2e4fa results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 01e504a2e4fa ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>