tty/amiserial: Add missing argument for tty_unlock()
commit 1cdbac10d29621afde11cafad4da4b2a8e6e1396 ("tty_lock: Localise the lock")
missed that c76d3f7c4f2e7e8ef6bc357d50d3bb0ea733efcb ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>